export const USERS_DATA = [
  {
    id: '1',
    activities: 'нет',
    productionTime: '80',
    warranties: '24',
    paymentTerms: '30',
    cost: '3700000',
    isOnline: true,
  },
  {
    id: '2',
    activities: 'нет',
    productionTime: '90',
    warranties: '24',
    paymentTerms: '100',
    cost: '3200000',
    isOnline: true,
  },
  {
    id: '3',
    activities: 'нет',
    productionTime: '75',
    warranties: '22',
    paymentTerms: '60',
    cost: '2800000',
    isOnline: true,
  },
  {
    id: '4',
    activities: 'нет',
    productionTime: '120',
    warranties: '36',
    paymentTerms: '50',
    cost: '2500000',
    isOnline: true,
  },
  {
    id: '5',
    activities: 'да',
    productionTime: '110',
    warranties: '30',
    paymentTerms: '70',
    cost: '2900000',
    isOnline: true,
  },
];
